### ISSUE TITLE
Actualizar fork

### ISSUE THREAD

**Issue by guillepaez53** [lbiedma/IntroProgramacionFCEUNC#1]
Luis, disculpá. Hay forma de actualizar el fork que hicimos en la clase 5 para que el repositorio me quede completo? Creo que en aquel momento o no estaba completo o lo hice mal. Estoy intentando actualizarlo ahora pero no encuentro una manera obvia (busqué en YouTube, y lo que encuentro es para hacerlo por comandos, puede ser?).

Gracias!
Guillermo

**Comment by guillepaez53** [comment]
Creo que ya lo encontré! fetch upstream

**Comment by lbiedma** [comment]
Exacto, esa es la respuesta!

https://stackoverflow.com/questions/7244321/how-do-i-update-or-sync-a-forked-repository-on-github
